var countries=[
    {
        id:1001,
        name:'America',
        states:[
            {
                id:1,
                name:'Alabama',
                cities:[
                    {
                        id:11,
                        name:'Addison',
                    },
                    {
                        id:12,
                        name:'Bear Creek',
                    },
                    {
                        id:13,
                        name:'Epes',
                    }
                    
                ]
            },
            {
                id:2,
                name:'Alaska',
                cities:[
                    {
                        id:11,
                        name:'Akutan',
                    },
                    {
                        id:12,
                        name:'Big Lake',
                    },
                    {
                        id:13,
                        name:'Gakona',
                    }
                    
                ]
            },
            {
                id:3,
                name:'Arizona',
                cities:[
                    {
                        id:11,
                        name:'Buckeye',
                    },
                    {
                        id:12,
                        name:'Congress',
                    },
                    {
                        id:13,
                        name:'Ehrenberg',
                    }
                    
                ]
            },
            {
                id:4,
                name:'Arkansas',
                cities:[
                    {
                        id:11,
                        name:'Altus',
                    },
                    {
                        id:12,
                        name:'Atkins',
                    },
                    {
                        id:13,
                        name:'Bigelow',
                    }
                    
                ]
            },
            {
                id:5,
                name:'California',
                cities:[
                    {
                        id:51,
                        name:'Los Angeles',
                    },
                    {
                        id:52,
                        name:'Sacramento',
                    },
                    {
                        id:53,
                        name:'San Francisco',
                    }
                    
                ]
            },
            {
                id:6,
                name:'Colorado',
                cities:[
                    {
                        id:11,
                        name:'Bayfield',
                    },
                    {
                        id:12,
                        name:'Blanca',
                    },
                    {
                        id:13,
                        name:'Collbran',
                    }
                    
                ]
            },
            {
                id:7,
                name:'Connecticut',
                cities:[
                    {
                        id:11,
                        name:'Andover',
                    },
                    {
                        id:12,
                        name:'Beacon Falls',
                    },
                    {
                        id:13,
                        name:'Bethlehem',
                    }
                    
                ]
            },
            {
                id:8,
                name:'Delaware',
                cities:[
                    {
                        id:11,
                        name:'Bear',
                    },
                    {
                        id:12,
                        name:'Clayton',
                    },
                    {
                        id:13,
                        name:'Delaware City',
                    }
                    
                ]
            },
            {
                id:9,
                name:'Florida',
                cities:[
                    {
                        id:11,
                        name:'Anna Maria',
                    },
                    {
                        id:12,
                        name:'Apopka',
                    },
                    {
                        id:13,
                        name:'Aventura',
                    }
                    
                ]
            },
            {
                id:10,
                name:'Georgia',
                cities:[
                    {
                        id:11,
                        name:'Albany',
                    },
                    {
                        id:12,
                        name:'Ambrose',
                    },
                    {
                        id:13,
                        name:'Bloomingdale',
                    }
                    
                ]
            },
            {
                id:11,
                name:'Hawaii',
                cities:[
                    {
                        id:11,
                        name:'Aiea',
                    },
                    {
                        id:12,
                        name:'Haleiwa',
                    },
                    {
                        id:13,
                        name:'Hanalei',
                    }
                    
                ]
            },
            {
                id:12,
                name:'Idaho',
                cities:[
                    {
                        id:11,
                        name:'Aberdeen',
                    },
                    {
                        id:12,
                        name:'Arimo',
                    },
                    {
                        id:13,
                        name:'Caldwell',
                    }
                    
                ]
            },
            {
                id:13,
                name:'Illinois',
                cities:[
                    {
                        id:11,
                        name:'Alexis',
                    },
                    {
                        id:12,
                        name:'Alsey',
                    },
                    {
                        id:13,
                        name:'Bensenville',
                    }
                    
                ]
            },
            {
                id:14,
                name:'Indiana',
                cities:[
                    {
                        id:11,
                        name:'Advance',
                    },
                    {
                        id:12,
                        name:'Amo',
                    },
                    {
                        id:13,
                        name:'Anderson',
                    }
                    
                ]
            },
            {
                id:15,
                name:'Iowa',
                cities:[
                    {
                        id:11,
                        name:'Algona',
                    },
                    {
                        id:12,
                        name:'Anamosa',
                    },
                    {
                        id:13,
                        name:'Boone',
                    }
                    
                ]
            },
            {
                id:16,
                name:'Kansas',
                cities:[
                    {
                        id:11,
                        name:'Abbyville',
                    },
                    {
                        id:12,
                        name:'Agra',
                    },
                    {
                        id:13,
                        name:'Alexander',
                    }
                    
                ]
            },
            {
                id:17,
                name:'Kentucky',
                cities:[
                    {
                        id:11,
                        name:'Adairville',
                    },
                    {
                        id:12,
                        name:'Alexandria',
                    },
                    {
                        id:13,
                        name:'Augusta',
                    }
                    
                ]
            },
            {
                id:18,
                name:'Louisiana',
                cities:[
                    {
                        id:11,
                        name:'Abbeville',
                    },
                    {
                        id:12,
                        name:'Albany',
                    },
                    {
                        id:13,
                        name:'Amite',
                    }
                    
                ]
            },
            {
                id:19,
                name:'Maine',
                cities:[
                    {
                        id:11,
                        name:'Andover',
                    },
                    {
                        id:12,
                        name:'Bangor',
                    },
                    {
                        id:13,
                        name:'Bethel',
                    }
                    
                ]
            },
            {
                id:20,
                name:'Maryland',
                cities:[
                    {
                        id:11,
                        name:'Arnold',
                    },
                    {
                        id:12,
                        name:'Barton',
                    },
                    {
                        id:13,
                        name:'Catonsville',
                    }
                    
                ]
            },
            {
                id:21,
                name:'Massachusetts',
                cities:[
                    {
                        id:11,
                        name:'Ashfield',
                    },
                    {
                        id:12,
                        name:'Ayer',
                    },
                    {
                        id:13,
                        name:'Bellingham',
                    }
                    
                ]
            },
            {
                id:22,
                name:'Michigan',
                cities:[
                    {
                        id:11,
                        name:'Algonac',
                    },
                    {
                        id:12,
                        name:'Alma',
                    },
                    {
                        id:13,
                        name:'Baroda',
                    }
                    
                ]
            },
            {
                id:23,
                name:'Minnesota',
                cities:[
                    {
                        id:11,
                        name:'Aitkin',
                    },
                    {
                        id:12,
                        name:'Albert Lea',
                    },
                    {
                        id:13,
                        name:'Alexandria',
                    }
                    
                ]
            },
            {
                id:24,
                name:'Mississippi',
                cities:[
                    {
                        id:11,
                        name:'Arcola',
                    },
                    {
                        id:12,
                        name:'Baldwyn',
                    },
                    {
                        id:13,
                        name:'Bay Springs',
                    }
                    
                ]
            },
            {
                id:25,
                name:'Missouri',
                cities:[
                    {
                        id:11,
                        name:'Adrian',
                    },
                    {
                        id:12,
                        name:'Advance',
                    },
                    {
                        id:13,
                        name:'Agency',
                    }
                    
                ]
            },
            {
                id:26,
                name:'Montana',
                cities:[
                    {
                        id:11,
                        name:'Absarokee',
                    },
                    {
                        id:12,
                        name:'Alberton',
                    },
                    {
                        id:13,
                        name:'Anaconda',
                    }
                    
                ]
            },
            {
                id:27,
                name:'Nebraska',
                cities:[
                    {
                        id:11,
                        name:'Adams',
                    },
                    {
                        id:12,
                        name:'Ainsworth',
                    },
                    {
                        id:13,
                        name:'Albion',
                    }
                    
                ]
            },
            {
                id:28,
                name:'Nevada',
                cities:[
                    {
                        id:11,
                        name:'Battle Mountain',
                    },
                    {
                        id:12,
                        name:'Beatty',
                    },
                    {
                        id:13,
                        name:'Blue Diamond',
                    }
                    
                ]
            },
            {
                id:29,
                name:'New Hampshire',
                cities:[
                    {
                        id:11,
                        name:'Acworth',
                    },
                    {
                        id:12,
                        name:'Alstead',
                    },
                    {
                        id:13,
                        name:'Alton',
                    }
                    
                ]
            },
            {
                id:30,
                name:'New Jersey',
                cities:[
                    {
                        id:11,
                        name:'Absecon',
                    },
                    {
                        id:12,
                        name:'Allamuchy',
                    },
                    {
                        id:13,
                        name:'Allendale',
                    }
                    
                ]
            },
            {
                id:31,
                name:'New Mexico',
                cities:[
                    {
                        id:11,
                        name:'Alamogordo',
                    },
                    {
                        id:12,
                        name:'Albuquerque',
                    },
                    {
                        id:13,
                        name:'Alcalde',
                    }
                    
                ]
            },
            {
                id:32,
                name:'New York',
                cities:[
                    {
                        id:11,
                        name:'Accord',
                    },
                    {
                        id:12,
                        name:'Adams Center',
                    },
                    {
                        id:13,
                        name:'Adams',
                    }
                    
                ]
            },
            {
                id:33,
                name:'North Carolina',
                cities:[
                    {
                        id:11,
                        name:'Aberdeen',
                    },
                    {
                        id:12,
                        name:'Ahoskie',
                    },
                    {
                        id:13,
                        name:'Alamance',
                    }
                    
                ]
            },
            {
                id:34,
                name:'North Dakota',
                cities:[
                    {
                        id:11,
                        name:'Abercrombie',
                    },
                    {
                        id:12,
                        name:'Adams',
                    },
                    {
                        id:13,
                        name:'Alexander',
                    }
                    
                ]
            },
            {
                id:35,
                name:'Ohio',
                cities:[
                    {
                        id:11,
                        name:'Aberdeen',
                    },
                    {
                        id:12,
                        name:'Ada',
                    },
                    {
                        id:13,
                        name:'Addyston',
                    }
                    
                ]
            },
            {
                id:36,
                name:'Oklahoma',
                cities:[
                    {
                        id:11,
                        name:'Ada',
                    },
                    {
                        id:12,
                        name:'Altus',
                    },
                    {
                        id:13,
                        name:'Anadarko',
                    }
                    
                ]
            },
            {
                id:37,
                name:'Oregon',
                cities:[
                    {
                        id:11,
                        name:'Adams',
                    },
                    {
                        id:12,
                        name:'Albany',
                    },
                    {
                        id:13,
                        name:'Arlington',
                    }
                    
                ]
            },
            {
                id:38,
                name:'Pennsylvania',
                cities:[
                    {
                        id:11,
                        name:'Aaronsburg',
                    },
                    {
                        id:12,
                        name:'Abbottstown',
                    },
                    {
                        id:13,
                        name:'Adamsburg',
                    }
                    
                ]
            },
            {
                id:39,
                name:'Rhode Island',
                cities:[
                    {
                        id:11,
                        name:'Ashaway',
                    },
                    {
                        id:12,
                        name:'Barrington',
                    },
                    {
                        id:13,
                        name:'Bradford',
                    }
                    
                ]
            },
            {
                id:40,
                name:'South Carolina',
                cities:[
                    {
                        id:11,
                        name:'Abbeville',
                    },
                    {
                        id:12,
                        name:'Aiken',
                    },
                    {
                        id:13,
                        name:'Alcolu',
                    }
                    
                ]
            },
            {
                id:41,
                name:'South Dakota',
                cities:[
                    {
                        id:11,
                        name:'Aberdeen',
                    },
                    {
                        id:12,
                        name:'Alcester',
                    },
                    {
                        id:13,
                        name:'Alexandria',
                    }
                    
                ]
            },
            {
                id:42,
                name:'Tennessee',
                cities:[
                    {
                        id:11,
                        name:'Adams',
                    },
                    {
                        id:12,
                        name:'Adamsville',
                    },
                    {
                        id:13,
                        name:'Alamo',
                    }
                    
                ]
            },
            {
                id:43,
                name:'Texas',
                cities:[
                    {
                        id:11,
                        name:'Abbott',
                    },
                    {
                        id:12,
                        name:'Abernathy',
                    },
                    {
                        id:13,
                        name:'Abilene',
                    }
                    
                ]
            },
            {
                id:44,
                name:'Utah',
                cities:[
                    {
                        id:11,
                        name:'Alpine',
                    },
                    {
                        id:12,
                        name:'American Fork',
                    },
                    {
                        id:13,
                        name:'Aneth',
                    }
                    
                ]
            },
            {
                id:45,
                name:'Vermont',
                cities:[
                    {
                        id:11,
                        name:'Albany',
                    },
                    {
                        id:12,
                        name:'Alburg',
                    },
                    {
                        id:13,
                        name:'Arlington',
                    }
                    
                ]
            },
            {
                id:46,
                name:'Virginia',
                cities:[
                    {
                        id:11,
                        name:'Abingdon',
                    },
                    {
                        id:12,
                        name:'Accomac',
                    },
                    {
                        id:13,
                        name:'Alberta',
                    }
                    
                ]
            },
            {
                id:47,
                name:'Washington',
                cities:[
                    {
                        id:11,
                        name:'Bellevue',
                    },
                    {
                        id:12,
                        name:'Kirkland',
                    },
                    {
                        id:13,
                        name:'Redmond',
                    }
                    
                ]
            },
            {
                id:48,
                name:'Washington DC',
                cities:[
                    {
                        id:11,
                        name:'Washington DC',
                    }
                    
                ]
               
            },
            {
                id:49,
                name:'West Virginia',
                cities:[
                    {
                        id:11,
                        name:'Albright',
                    },
                    {
                        id:12,
                        name:'Alderson',
                    },
                    {
                        id:13,
                        name:'Alum Creek',
                    }
                    
                ]
            },
            {
                id:50,
                name:'Wisconsin',
                cities:[
                    {
                        id:11,
                        name:'Abbotsford',
                    },
                    {
                        id:12,
                        name:'Abrams',
                    },
                    {
                        id:13,
                        name:'Adams',
                    }
                    
                ]
            },
            {
                id:51,
                name:'Wyoming',
                cities:[
                    {
                        id:11,
                        name:'Afton',
                    },
                    {
                        id:12,
                        name:'Alpine',
                    },
                    {
                        id:13,
                        name:'Alta',
                    }
                    
                ]
            }

        ]

    },
    {
        id:1002,
        name:'China',
        states:[
            {
                id:201,
                name:'Guangdong',
                cities:[
                    {
                        id:11,
                        name:'Foshan',
                    },
                    {
                        id:12,
                        name:'Guangzhou',
                    },
                    {
                        id:13,
                        name:'Shenzhen',
                    }
                    
                ]
            },
            {
                id:202,
                name:'Hubei',
                cities:[
                    {
                        id:11,
                        name:'Huangshi',
                    },
                    {
                        id:12,
                        name:'Shiyan',
                    },
                    {
                        id:13,
                        name:'Yichang',
                    }
                    
                ]
            },
            {
                id:203,
                name:'Jiangsu',
                cities:[
                    {
                        id:11,
                        name:'Nanjing',
                    },
                    {
                        id:12,
                        name:'Taizhou',
                    },
                    {
                        id:13,
                        name:'Zhenjiang',
                    }
                    
                ]
            }

        ]

    }

];
window.addEventListener('load', (event) => {
    for(var c of countries){
    var option = new Option(c.name,c.id);
    document.getElementById('Country').add(option);
    }
  document.getElementById('Country').addEventListener('change',function(){
    var id= document.getElementById('Country').value;
    console.log(id);
    document.getElementById('State').length=1;
    var code = document.getElementById('Code');
    if(id=='1001'){
        code.style.display='block';
    }else{
        code.style.display='none';
    }
    for(var c of countries){
        if(c.id==id){
            for(var s of c.states){
                var option = new Option(s.name,s.id);
                document.getElementById('State').add(option);
            }
            break;
        }
    }
    });
    document.getElementById('State').addEventListener('change',function(){
        var id= document.getElementById('State').value;
        console.log(id);
        document.getElementById('City').length=1;
        for(c of countries){
            for(var s of c.states){
            if(s.id==id){
                console.log(c.states);
                for(var ci of s.cities){
                    var option = new Option(ci.name,ci.id);
                    document.getElementById('City').add(option);
                }
                break;
            }
            
        } 
        }
       
        });


  });

